### ISSUE TITLE
physics_test.py fails

### ISSUE THREAD

**Issue by erwincoumans** [google/brax#1]
Congrats, this is a very nice repository!

Running the physics_test.py has a few failing tests.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\miniconda3\lib\site-packages\absl\testing\parameterized.py", line 316, in bound_param_test
    return test_method(self, *testcase_params)
  File "D:\dev\brax_official\brax\tests\physics_test.py", line 54, in test_pendulum_period
    config.dt = 2 * jnp.pi * jnp.sqrt((.4 * radius**2 + 1.) / 9.8)
  File "D:\miniconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 715, in field_setter
    raise TypeError(
TypeError: Cannot set brax.Config.dt to DeviceArray(2.0086575, dtype=float32): DeviceArray(2.0086575, dtype=float32) has type <class 'jaxlib.xla_extension.DeviceArray'>, but expected one of: numbers.Real
```

Using a hard coded config.dt = 1.0066762 makes the test pass

This is on Windows 10, using latest JAX master on CUDA 11.0, cudnn 8.1.1 (but same for older JAX 0.1.61).

By the way, had some fun training the Ant using a local runtime on Windows, attached are the timings (RTX 2080)
also created some JAX precompiled wheels of latest master branch for other poor Windows souls, see
https://github.com/erwincoumans/jax/releases/tag/jax-v0.1.68_windows
![ant_trained](https://user-images.githubusercontent.com/725468/120878230-d45f7700-c56f-11eb-985a-7983985029f5.png)

**Comment by erikfrey** [comment]
Hi Erwin - thanks for the bug report and congrats on opening Brax's very first issue!  🎉 🎉 🎉 

I was able to repro your issue on my Windows machine.  This is probably some subtle DeviceArray type promotion bug that only happens on Windows.  Rather than chase it down on the jax side, we just coerced the type in the test, so should be fixed as of 617f3d6eea5d16b4c6bcc8103839f0a4e353791f.

Please let us know if that doesn't get the test going for you.

And yes I feel your pain re: JAX wheel - I wasted a few days last quarter doing the same thing.  Maybe we can attract enough windows users to convince jax to start building windows wheels?     :-)
