### ISSUE TITLE
Installing brax.experimental locally

### ISSUE THREAD

**Issue by KarolisRam** [google/brax#177]
After playing around with the Braxlines Composer using this [Colab](https://colab.research.google.com/github/google/brax/blob/main/notebooks/composer/composer.ipynb), I wanted to try it locally.  

However `pip install git+https://github.com/google/brax.git@main` doesn't install the `brax.experimental` part. I assume this is intentional? How does it work fine in Colab though?  

I fixed it by cloning the repo and doing `pip install -e .` instead. Is this the right way to do it? Maybe there should be something like `pip install brax[experimental]`?

**Comment by erikfrey** [comment]
Hi @KarolisRam - good catch!  This is now fixed in 984855ec367e50ab3d619025ae23d0c8359e232d - you should now be able to run `pip install git+https://github.com/google/brax.git@main` and then `import brax.experimental`

Upon our next release, this will also be available via `pip install brax`.

Closing, but please reach out if you have any other issues.
