### ISSUE TITLE
Porting PyBullet Env into Brax

### ISSUE THREAD

**Issue by bhuv-z** [google/brax#85]
I am porting a biped robot and have been able to run the urdf_converter and have the robot's configuration parsed. I'm using the `humanoid.py` env as the base for this port. All the joints have been included in the config. Is there documentation on how the config is parsed and the parts are loaded? I see that the config for the humanoid simulation has 10 joins, while ``self.sys.joints`` has 3 elements. My robot's config has 6 joints and `self.sys.joints` only has 1 element. I'm trying to understand how they are getting loaded into System.joints from the config. Any help would be appreciated!

**Comment by erwincoumans** [comment]
Can you attach the (zipped) urdf and resulting config?

**Comment by erikfrey** [comment]
This can confusing - `sys.joints` is an array of `Joint` structs, each of which can be batched to actually represent many actual joints in the system.  When `sys.joints` contains more than one element, it's because each element is a different batched `Joint` subtype - `Revolute`, `Universal`, `Spherical`, each of which have slightly different shapes.

Closing this issue, but please reach out if you have any more questions.
